In [1]:

import numpy as np
mia_lista = np.array([1,2,3,4,5,6])
print(type(mia_lista))

print(np.arange(-10,10,2))
print(np.linspace(0,100,5))
print(mia_lista.argmin())
print(mia_lista.argmax())
print(mia_lista.reshape(3,2))

matrice = np.array([[10,11,12,13],[20,21,22,23],[30,31,32,33]])
print(matrice)
print(matrice[0][1])
print(matrice[:,1:])
print(matrice.size)
print(matrice + 6)

<class 'numpy.ndarray'>
[-10  -8  -6  -4  -2   0   2   4   6   8]
[  0.  25.  50.  75. 100.]
0
5
[[1 2]
 [3 4]
 [5 6]]
[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
11
[[11 12 13]
 [21 22 23]
 [31 32 33]]
12
[[16 17 18 19]
 [26 27 28 29]
 [36 37 38 39]]


In [2]:
from random import randint as rnd
li = [rnd(0, 1000) for a in range(0,100)]
print(li)

[366, 175, 420, 669, 343, 477, 227, 694, 108, 701, 148, 173, 914, 311, 437, 247, 560, 354, 659, 94, 124, 559, 493, 498, 517, 976, 658, 344, 882, 246, 579, 543, 522, 324, 428, 690, 300, 494, 561, 836, 207, 737, 171, 849, 963, 386, 200, 382, 956, 558, 146, 639, 927, 900, 674, 600, 289, 247, 380, 301, 907, 705, 119, 540, 511, 638, 241, 709, 506, 559, 645, 724, 691, 508, 964, 527, 436, 912, 593, 756, 345, 282, 32, 739, 552, 167, 983, 186, 638, 141, 971, 126, 175, 797, 817, 808, 413, 396, 721, 282]


In [3]:
from random import randint as rando
li = [rando(0, 1000) for a in range(0,100)]
print([b for b in li if b % 2 != 0 ])

[891, 957, 275, 835, 631, 93, 299, 865, 287, 191, 541, 657, 697, 243, 233, 535, 669, 379, 77, 325, 319, 633, 331, 17, 279, 637, 417, 147, 415, 691, 375, 535, 227, 925, 71, 837, 341, 965, 393, 25, 415, 939, 775, 549, 293, 745, 359, 107, 31, 641, 599, 71, 337]


In [7]:
ln = [2,4,6,7,12,15,18,24,33,44,57,64,79,82,93,107]
l2 = []

for a in ln:
    l2.append(a**2)
print(l2)    
l3 = [a*2 for a in ln ]
print(l3)
l4 = ["Pari" if a % 2 == 0 else "Dispari" for a in ln]
#if nella stessa riga di lista; parte dichiarativa del Python
print(l4)
l5 = [a for a in ln if a % 2!= 0]
#filtraggio
print(l5)

[4, 16, 36, 49, 144, 225, 324, 576, 1089, 1936, 3249, 4096, 6241, 6724, 8649, 11449]
[4, 8, 12, 14, 24, 30, 36, 48, 66, 88, 114, 128, 158, 164, 186, 214]
['Pari', 'Pari', 'Pari', 'Dispari', 'Pari', 'Dispari', 'Pari', 'Pari', 'Dispari', 'Pari', 'Dispari', 'Pari', 'Dispari', 'Pari', 'Dispari', 'Dispari']
[7, 15, 33, 57, 79, 93, 107]


In [15]:
matrice = np.array([[10,11,12,13],[20,21,22,23],[30,31,32,33]])
print(matrice)
print(matrice[0][1])
print(matrice[:,1:])
print(matrice.size)
print(matrice + 6)
nn = [1, 2, 3, 5, 33, 40, 50, 75]
c = np.concatenate([mia_lista, nn])
print(c)
print(np.vstack(nn))
print(np.hstack(nn))
print(np.split(c, [6,10]))

[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
11
[[11 12 13]
 [21 22 23]
 [31 32 33]]
12
[[16 17 18 19]
 [26 27 28 29]
 [36 37 38 39]]
[ 1  2  3  4  5  6  1  2  3  5 33 40 50 75]
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [33]
 [40]
 [50]
 [75]]
[ 1  2  3  5 33 40 50 75]
[array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 5]), array([33, 40, 50, 75])]


In [18]:
# mat è una matrice di 3 righe e 4 colonna
mat = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]) 
#per accedere a singoli elementi, posso per esempio
print(mat[:,:4])
print(mat[2][1])

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]
11


In [19]:
linear_data = np.array([x for x in range(27)])
reshaped_data = linear_data.reshape((3, 3, 3))
print(linear_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [21]:
linear_data = np.array([x for x in range(27)])
reshaped_data = linear_data.reshape((3, 3, 3))
print(reshaped_data)
#ora ho una matrice di tre dimensioni contente 9 arrays con 3 numeri ciascuno (da 0 a 26)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [53]:
import numpy as np
rivetti = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
lunghezza = 28.75
buchi = lunghezza/14
arrot = np.round(buchi,2)
print(np.arange(0,lunghezza,arrot))

[ 0.    2.05  4.1   6.15  8.2  10.25 12.3  14.35 16.4  18.45 20.5  22.55
 24.6  26.65 28.7 ]


In [38]:
import numpy as nd
rows, cols = 3,4
matrix = nd.zeros((rows, cols), dtype = int)

matrix[0, 0] = 1
matrix[0, 1] = 1
matrix[0, 2] = 1
matrix[0, 3] = 1
matrix[1, 0] = 5
matrix[1, 1] = 1
matrix[1, 2] = 1
matrix[1, 3] = 1
matrix[2, 0] = 20
matrix[2, 1] = -4
matrix[2, 2] = 0
matrix[2, 3] = 42

print(matrix)

[[ 1  1  1  1]
 [ 5  1  1  1]
 [20 -4  0 42]]


In [40]:
import numpy as np
tabella = np.array([[10,22,21,8,9],[9,42,3,18,11],[5,4,30,12,29],[37,31,7,2,26],[8,6,4,33,15]])
print(tabella)

[[10 22 21  8  9]
 [ 9 42  3 18 11]
 [ 5  4 30 12 29]
 [37 31  7  2 26]
 [ 8  6  4 33 15]]


In [51]:
import numpy as np
tabella = np.array([[10,22,21,8,9],[9,42,3,18,11],[5,4,30,12,29],[37,31,7,2,26],[8,6,4,33,15]])
min = tabella.min()
max = tabella.max()
print(min)
print(max)
tabella1 = tabella - min
tabella2 = ((tabella1/max) - min)
tabella3 = np.round(tabella2, 3)
print(tabella1)
print(tabella3)

2
42
[[ 8 20 19  6  7]
 [ 7 40  1 16  9]
 [ 3  2 28 10 27]
 [35 29  5  0 24]
 [ 6  4  2 31 13]]
[[-1.81  -1.524 -1.548 -1.857 -1.833]
 [-1.833 -1.048 -1.976 -1.619 -1.786]
 [-1.929 -1.952 -1.333 -1.762 -1.357]
 [-1.167 -1.31  -1.881 -2.    -1.429]
 [-1.857 -1.905 -1.952 -1.262 -1.69 ]]
